config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: >-
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
metadata:
  site_url: 'https://katedee-halide.netlify.app'
  site_title: Kate Drwecka
  site_subtitle_1: Cartoonist | Designer
  site_subtitle_2: "Montreal, \U0001F341"
  site_description: >
    Lover of moody and atmospheric comics and graphics. Currently working on The Death of Baba Yaga.
  site_email: katedrwecka@gmail.com
  site_social_url: 'https://bsky.app/profile/thisiskatedee.bsky.social'
  site_icon_svg: /assets/uploads/favicon.svg
  site_icon_png: ''
  site_ga4_id: ''
  site_social_title: Bluesky
  seo:
    site_title: Kate Drwecka
    site_description: >-
      Lover of moody and atmospheric comics and graphics. Currently working on The Death of Baba Yaga.
    no_index: false
theme:
  theme_layout:
    space_scale: 80
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#542BFF'
    background_dark: '#101010'
    text_dark: '#E1E1E1'
    link_dark: '#FF2079'
  theme_typography:
    font: Overpass Mono
    font_weight: 400
    font_scale: 120
    line_height_scale: 100
  theme_features:
    enable_dark_mode: true
    item_output_limit: 48
    transition_duration: 300
    show_project_year: true
    show_project_grid_titles: true
images:
  avif:
    enabled: true
    quality: 75
  webp:
    enabled: true
    quality: 75
  jpeg:
    enabled: true
    quality: 75
  
